---
deployment:
  tasks:
    - /bin/cp index.html /home/valourcon/public_html/
    - /bin/cp 404.html /home/valourcon/public_html/
    - /bin/cp favicon.svg /home/valourcon/public_html/
    - /bin/cp robots.txt /home/valourcon/public_html/
    - /bin/cp sitemap-0.xml /home/valourcon/public_html/
    - /bin/cp sitemap-index.xml /home/valourcon/public_html/
    - /bin/cp -R about /home/valourcon/public_html/
    - /bin/cp -R assets /home/valourcon/public_html/
    - /bin/cp -R contact /home/valourcon/public_html/
    - /bin/cp -R images /home/valourcon/public_html/
    - /bin/cp -R projects /home/valourcon/public_html/
    - /bin/cp -R services /home/valourcon/public_html/
