---
deployment:
  tasks:
    - export DEPLOYPATH=/home/valourcon/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap-0.xml $DEPLOYPATH
    - /bin/cp sitemap-index.xml $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R contact $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R services $DEPLOYPATH
